# Utiliser une image Nginx officielle
FROM nginx:latest

# Copier le fichier de configuration Nginx personnalisé
COPY ./docker/nginx/default.conf /etc/nginx/conf.d/default.conf

# Exposer le port 80 pour Nginx
EXPOSE 80